config/routes.rb
Rails.application.routes.draw do

  # 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

   root to: "homes#top"
   get 'about' => 'homes#about'

  scope module: :public do

    post 'orders/confirm'
    get 'orders/thanks'
    delete 'cart_items/destroy_all'
    get "/customers/my_page" => "customers#show"
    get "/customers/confirm" => "customers#confirm"
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:show, :edit, :update,]

    resources :items, only: [:index, :show,]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :show, :index, :create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]



  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:new, :index, :show, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def full_address
    "〒" + self.postal_code + "　" + self.address + "　" + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
 self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirmation: 1, making: 2, preparation: 3, shipped: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { not_started: 0, waiting: 1, making: 2, completed: 3 }

  belongs_to :item
  belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
   @genres = Genre.all
    @genre = Genre.new
  end

  def create
   @genre = Genre.new(genre_params)
   if @genre.save
     redirect_to admin_genres_path(@genre.id)
   else
     @genres = Genre.all
     render :index
   end
  end

  def edit
   @genre = Genre.find(params[:id])
  end

  def update
   @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     redirect_to admin_genres_path(@genre.id)
    else
     render :edit
    end
  end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!

  def new
   @item = Item.new
  end

  def create
   @item = Item.new(item_params)
    if @item.save
       redirect_to admin_item_path(@item)
    else
       render :new
    end
  end

  def index
   @items = Item.all.page(params[:page])
  end

  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item)
    else
     render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @items = Item.all.order(created_at: :desc)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mb-4 bg-light">
      <h3><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h3>
    </div>
    <div class="col-md-7">
    </div>
  </div>

  <div class="text-danger">
    <% if @customer.errors.any? %>
      エラーが発生しました
    <% end %>
  </div>

  <%= form_with model:@customer, url:admin_customer_path, method: :PATCH, local: true do |f| %>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">会員ＩＤ</label>
      <div class="col-sm-10 d-flex align-items-center">
        <%= @customer.id %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_name" class="col-sm-2 col-form-label">氏名</label>
      <div class="col-sm-10">
        <%= f.text_field :last_name, class:"col-4" %>
        <%= f.text_field :first_name, class:"col-4" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_name_kana" class="col-sm-2 col-form-label">フリガナ</label>
      <div class="col-sm-10">
        <%= f.text_field :last_name_kana, class:"col-4" %>
        <%= f.text_field :first_name_kana, class:"col-4" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_postal_code" class="col-sm-2 col-form-label">郵便番号</label>
      <div class="col-sm-10">
        <%= f.text_field :postal_code, class:"col-4" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_address" class="col-sm-2 col-form-label">住所</label>
      <div class="col-sm-10">
        <%= f.text_field :address, class:"col-7" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_telephone_number" class="col-sm-2 col-form-label">電話番号</label>
      <div class="col-sm-10">
        <%= f.text_field :telephone_number, class:"col-4" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_email" class="col-sm-2 col-form-label">メールアドレス</label>
      <div class="col-sm-10">
        <%= f.text_field :email, class:"col-4" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_is_active" class="col-sm-2 col-form-label">会員ステータス</label>
      <div class="col-sm-10 d-flex align-items-center">
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, "true" %>
          有効
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, "false" %>
          退会
        </div>
      </div>
    </div>


    <div class="form-group row">
      <div class="col-sm-10">
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
    </div>
<% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mb-3 bg-light">
      <h3>会員一覧</h3>
    </div>
    <div class="col-md-8">
    </div>
  </div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </th>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_active == true %>
                  <div class="text-success font-weight-bold">
                    有効
                  </div>
                <% else %>
                  <div class="text-muted font-weight-bold">
                    退会
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-1"></div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mb-3 bg-light">
      <h3><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h3>
    </div>
    <div class="col-md-8">
    </div>
  </div>

  <div class="row">
    <table class="table table-borderless col-6">
      <tr>
        <th class="col-sm-2">会員ID</th>
        <td class="col-sm-3" ><%= @customer.id %></td>
      </tr>

      <tr>
        <th class="col-sm-2">氏名</th>
        <td class="col-sm-3" ><%= @customer.last_name %>　<%= @customer.first_name %></td>
      </tr>

      <tr>
        <th class="col-sm-2">フリガナ</th>
        <td class="col-sm-3" ><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
      </tr>

      <tr>
        <th class="col-sm-2">郵便番号</th>
        <td class="col-sm-3" ><%= @customer.postal_code %></td>
      </tr>

      <tr>
        <th class="col-sm-2">住所</th>
        <td class="col-sm-3" ><%= @customer.address %></td>
      </tr>

      <tr>
        <th class="col-sm-2">電話番号</th>
        <td class="col-sm-3" ><%= @customer.telephone_number %></td>
      </tr>

      <tr>
        <th class="col-sm-2">メールアドレス</th>
        <td class="col-sm-3" ><%= @customer.email %></td>
      </tr>

      <tr>
        <th class="col-sm-2">会員ステータス</th>
          <% if @customer.is_active == true %>
            <td class="text-success font-weight-bold col-sm-3">
              有効
            </td>
          <% else %>
            <td class="text-muted font-weight-bold col-sm-3">
              退会
            </td>
          <% end %>
      </tr>
    </table>
  </div>
  </br>
  <div class="row">
    <div class="col-2">
    <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>
    </div>
    <div class="col-3">
    <%#= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>