config/routes.rb
Rails.application.routes.draw do

  # 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

   root to: "homes#top"
   get 'about' => 'homes#about'

  scope module: :public do

    post 'orders/confirm'
    get 'orders/thanks'
    delete 'cart_items/destroy_all'
    get "/customers/my_page" => "customers#show"
    get "/customers/confirm" => "customers#confirm"
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:show, :edit, :update,]

    resources :items, only: [:index, :show,]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :show, :index, :create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]



  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:new, :index, :show, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def full_address
    "〒" + self.postal_code + "　" + self.address + "　" + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
 self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirmation: 1, making: 2, preparation: 3, shipped: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { not_started: 0, waiting: 1, making: 2, completed: 3 }

  belongs_to :item
  belongs_to :order
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
   @genres = Genre.all
    @genre = Genre.new
  end

  def create
   @genre = Genre.new(genre_params)
   if @genre.save
     redirect_to admin_genres_path(@genre.id)
   else
     @genres = Genre.all
     render :index
   end
  end

  def edit
   @genre = Genre.find(params[:id])
  end

  def update
   @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     redirect_to admin_genres_path(@genre.id)
    else
     render :edit
    end
  end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!

  def new
   @item = Item.new
  end

  def create
   @item = Item.new(item_params)
    if @item.save
       redirect_to admin_item_path(@item)
    else
       render :new
    end
  end

  def index
   @items = Item.all.page(params[:page])
  end

  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item)
    else
     render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(status: params[:order][:status])
    redirect_to admin_order_path(@order.id)
  end


  private

  def order_params
    params.require(:order).permit(:customer_id, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @items = Item.all.order(created_at: :desc)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<%= form_with model: [:admin,@genre] do |f| %>
 <div>
   <label>ジャンル名</label>
   <%= f.text_field :name %>
  </div>

  <div>
   <%= f.submit '変更を保存' %>
  </div>
<% end %>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mb-3 bg-light">
      <h3>ジャンル一覧・追加</h3>

<%= form_with model: [:admin,@genre] do |f| %>
 <div>
   <label>ジャンル名</label>
   <%= f.text_field :name %>
  </div>

  <div>
   <%= f.submit '新規登録', class: "btn btn-success" %>
  </div>
<% end %>


 <table>
  <thead>
    <tr>
      <th>ジャンル</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
   <%@genres.each do |genre|%>
    <tr>
     <td><%= genre.name %></td>
     <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
    </tr>

   <%end%>
  </tbody>
 </table>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/edit.html.erb
<h2 class="mt-3">商品編集</h2>

  <%= form_with model: [:admin,@item] do |f| %>

    <div class="form-group">
      <label for="item_image">商品画像</label>
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
      <div class ="field_with_errors">
        <label for ="item-name">商品名</label>
      </div>
      <div class ="field_with_errors">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="form-group">
      <label for="item-introduction">商品説明</label>
      <div class ="field_with_errors">
        <%= f.text_area :introduction %>
      </div>
    </div>
    <div class="form-group">
      <label for="item-genre">ジャンル</label>
      <div class ="field_with_errors">
       <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
      </div>
    </div>
    <div class="form-group">
      <label for="item-price">税抜価格</label>
      <div class ="field_with_errors">
        <%= f.text_field :price %>円
      </div>
    </div>

     <div class="form-group row">
      <label for="is_active" class="col-sm-2 col-form-label">販売ステータス</label>
      <div class="col-sm-10 d-flex align-items-center">
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, "true" %>販売中
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, "false" %>販売停止中
        </div>
      </div>
    </div>

    <div class="form-group">
      <input type="submit" name="commit" value="変更を保存" class="btn btn-success" data-disable-with="変更を保存" />
    </div>
  <% end %>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mb-3 bg-light">
      <h3>商品一覧</h3>
    </div>
    <div class="col-md-5">
    </div>
    <div class="col col-md-3 mb-3 text-right">
      <%= link_to "＋", new_admin_item_path, class: "btn btn-outline-dark" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th></th>
            <th></th>
            <th>ステータス</th>
          </th>
        </thead>

        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item.id) %></td>
              <td><%= item.price.to_s(:delimited) %>円</td>
              <td><%= item.genre.name %></td>
              <td></td>
              <td></td>
              <td>
                <% if item.is_active == true %>
                  <div class="text-success font-weight-bold">
                    販売中
                  </div>
                  <% else %>
                  <div class="text-muted font-weight-bold">
                    販売停止中
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-1"></div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<h2 class="mt-3">商品新規登録</h2>

  <%= form_with model: [:admin,@item] do |f| %>

    <div class="form-group">
      <label for="item_image">商品画像</label>
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
      <div class ="field_with_errors">
        <label for ="item-name">商品名</label>
      </div>
      <div class ="field_with_errors">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="form-group">
      <label for="item-introduction">商品説明</label>
      <div class ="field_with_errors">
        <%= f.text_area :introduction %>
      </div>
    </div>
    <div class="form-group">
      <label for="item-genre">ジャンル</label>
      <div class ="field_with_errors">
       <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
      </div>
    </div>
    
    <div class="form-group">
      <label for="item-price">税抜価格</label>
      <div class ="field_with_errors">
        <%= f.text_field :price %>円
      </div>
    </div>

    <div class="form-group row">
      <label for="is_active" class="col-sm-2 col-form-label">販売ステータス</label>
      <div class="col-sm-10">
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, "true" %>
          販売中
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, "false" %>
          販売停止中
        </div>
      </div>
    </div>

    <div class="form-group">
      <input type="submit" name="commit" value="新規登録" class="btn btn-success" data-disable-with="新規登録" />
    </div>
  <% end %>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mb-3 bg-light">
      <h3>商品詳細</h3>
    </div>
    <div class="col-md-8">
    </div>
  </div>
  </br>

  <div class="row">
    <div class="col-3">
      <%= image_tag @item.get_image(200,200) %>
    </div>

    <table class="col-6">
      <tr>
        <th class="col-sm-2">商品名</th>
        <td class="col-sm-3" ><%= @item.name %></td>
      </tr>
      <tr>
        <th class="col-sm-2">商品説明</th>
        <td class="col-sm-3"><%= @item.introduction %></td>
      </tr>
      <tr>
        <th class="col-sm-2">ジャンル</th>
        <td class="col-sm-3"><%= @item.genre.name %></td>
      </tr>

      <tr>
        <th class="col-sm-2">税込価格 </br>(税抜価格)</th>
        <td class="col-sm-3"><%= (@item.price * 1.1) .to_i.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>) 円</td>
      </tr>

      <tr>
        <th class="col-sm-2 col-form-p">販売ステータス</th>
          <% if @item.is_active == true %>
            <td class="text-success font-weight-bold col-sm-3">
              販売中
            </td>
          <% else %>
            <td class="text-muted font-weight-bold col-sm-3">
              販売停止中
            </td>
          <% end %>
      </tr>
    </table>
  </div>
  </br>
  <div class="row justify-content-center">
    <%= link_to "編集する", edit_admin_item_path, class: "btn btn-success" %>
  </div>

</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mb-3 bg-light">
      <h3>注文履歴詳細</h3>
    </div>
    <div class="col-md-8">
    </div>
  </div>

  <div class="row">
    <table class="table table-borderless table-sm col-8">
      <tr>
        <th style="width: 30%">購入者</th>
        <td style="width: 70%">
          <%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order.customer.id) %>
        </td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td>
          〒<%= @order.postal_code %>
          　<%= @order.address %>
        </td>
      </tr>
      <tr>
        <th></th>
        <td>
          <%= @order.name %>
        </td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td>
          <%= @order.payment_method_i18n %>
        </td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td>
          <%= form_with model:@order, url:admin_order_path(@order.id), method: :PATCH, local: true do |f| %>
            <%= f.select :status, Order.statuses_i18n.keys.map{|k| [I18n.t("enums.order.status.#{k}"), k]} %>
            <%= f.submit "更新", class: "btn btn-success ml-3 btn-sm" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  </br>
  <div class="row">
    <table class="table table-sm col-7">
      <thead class="bg-light">
        <tr>
          <th style="width: 25%">商品名</th>
          <th style="width: 15%">単価(税込)</th>
          <th style="width: 15%">数量</th>
          <th style="width: 15%">小計</th>
          <th style="width: 20%">製作ステータス</th>
          <th style="width: 10%"></th>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>
            <td>
              <%= form_with model:order_detail, url:admin_order_detail_path(order_detail.id), method: :PATCH, local: true do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
            </td>
            <td>
                <%= f.submit "更新", class: "btn btn-success ml-3 btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="col-1">
    </div>
    <table class="table table-borderless table-sm col-3">
      <tbody>
        <tr>
          <th class="bg-light" style="width: 50%">商品合計</th>
          <td style="width: 50%"><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %>円</td>
        </tr>
        <tr>
        <th class="bg-light" style="width: 50%">送料</th>
        <td style="width: 50%"><%= @order.shipping_cost %>円</td>
        </tr>
        <th class="bg-light">請求金額合計</th>
        <td><%= @order.total_payment.to_s(:delimited) %>円</td>
        </tr>
    </table>
  </div>