config/routes.rb
Rails.application.routes.draw do

  # 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

   root to: "homes#top"
   get 'about' => 'homes#about'

  scope module: :public do

    post 'orders/confirm'
    get 'orders/thanks'
    delete 'cart_items/destroy_all'
    get "/customers/my_page" => "customers#show"
    get "/customers/confirm" => "customers#confirm"
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:show, :edit, :update,]

    resources :items, only: [:index, :show,]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :show, :index, :create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]



  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:new, :index, :show, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def full_address
    "〒" + self.postal_code + "　" + self.address + "　" + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
 self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirmation: 1, making: 2, preparation: 3, shipped: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { not_started: 0, waiting: 1, making: 2, completed: 3 }

  belongs_to :item
  belongs_to :order
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
   @genres = Genre.all
    @genre = Genre.new
  end

  def create
   @genre = Genre.new(genre_params)
   if @genre.save
     redirect_to admin_genres_path(@genre.id)
   else
     @genres = Genre.all
     render :index
   end
  end

  def edit
   @genre = Genre.find(params[:id])
  end

  def update
   @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     redirect_to admin_genres_path(@genre.id)
    else
     render :edit
    end
  end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!

  def new
   @item = Item.new
  end

  def create
   @item = Item.new(item_params)
    if @item.save
       redirect_to admin_item_path(@item)
    else
       render :new
    end
  end

  def index
   @items = Item.all.page(params[:page])
  end

  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item)
    else
     render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(status: params[:order][:status])
    redirect_to admin_order_path(@order.id)
  end


  private

  def order_params
    params.require(:order).permit(:customer_id, :status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @items = Item.all.order(created_at: :desc)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mb-3 bg-light">
      <h3>注文履歴一覧</h3>
    </div>
    <div class="col-md-8">
    </div>
  </div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th style="width: 30%">購入日時</th>
            <th style="width: 30%">購入者</th>
            <th style="width: 20%">注文個数</th>
            <th style="width: 20%">注文ステータス</th>
          </th>
        </thead>
        
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"),admin_order_path(order.id) %></td>
              <td><%= order.name %></td>
              <td><%= order.order_details.sum(:amount) %></td>
              <td><%= order.status_i18n %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <div class="col-md-1"></div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="text-center">
  
  <h1>About</h1>
  </br>
  <p>ながのCAKEは全国配達可能なケーキ屋さんです。</p>
  <p>お子様からお年寄りの方までお召し上がりいただけるよう、</p>
  <p>様々なバリエーションをご用意しております。</p>
  <p>また、全国へ配送可能ですので「いつ」でも「どこ」でもご注文いただけます。</p>
  <p>ぜひご注文ください。</p>
  </br>
  
</div>

app/views/homes/top.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-2">
      <%#= render 'public/search', genres: @genres%>
    </div>
    <div class="col-md-1">
    </div>

    <div class="col-md-9">
      <div class="jumbotron">
        <div class="bg_text text-center">
          <p>ようこそ、ながのCAKEへ！</p>
          <p>このサイトは、ケーキ販売のECサイトになります。</p>
          <p>会員でない方も商品の閲覧はできますが</p>
          <p>購入には会員登録が必要になります。</p>
        </div>
      </div>

      <div class="row mx-auto">
      <h3>新着商品</h3>
      </div>

      <div class="row">
      <% @items.first(4).each do |item| %>
        <div class="col-sm-3">
          <%= link_to item_path(item.id) do %>
              <%= image_tag item.get_image(150,150) %></br>
              <%= item.name %></br>
              ￥<%= item.price.to_s(:delimited) %>
            <% end %>
        </div>
      <% end %>
      </div>

      <div class="text-right">
      <%= link_to "全ての商品を見る＞", items_path %>
      </div>
    </div>