config/routes.rb
Rails.application.routes.draw do

  # 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

   root to: "homes#top"
   get 'about' => 'homes#about'

  scope module: :public do

    post 'orders/confirm'
    get 'orders/thanks'
    delete 'cart_items/destroy_all'
    get "/customers/my_page" => "customers#show"
    get "/customers/confirm" => "customers#confirm"
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:show, :edit, :update,]

    resources :items, only: [:index, :show,]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :show, :index, :create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]



  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:new, :index, :show, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def full_address
    "〒" + self.postal_code + "　" + self.address + "　" + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
 self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirmation: 1, making: 2, preparation: 3, shipped: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { not_started: 0, waiting: 1, making: 2, completed: 3 }

  belongs_to :item
  belongs_to :order
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!

  def new
   @item = Item.new
  end

  def create
   @item = Item.new(item_params)
    if @item.save
       redirect_to admin_item_path(@item)
    else
       render :new
    end
  end

  def index
   @items = Item.all.page(params[:page])
  end

  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item)
    else
     render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @items = Item.all.order(created_at: :desc)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg ">
        <div class="container">
          <%= link_to  "nagano_cake", root_path  %>
            <%#= image_tag "alexandra-khudyntseva-hXqbSgOPjSI-unsplash", size: "50x50" %>
          <ul class = "navbar-nav ml-auto m-3">
            <% if customer_signed_in? %>
              <li class="d-flex align-items-center mr-5">
                ようこそ、<%= current_customer.last_name %>さん！
              </li>
              <li class="mr-3">
                <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "カート", cart_items_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %>
              </li>

            <% elsif admin_signed_in? %>
              <li class="mr-3">
                <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "注文履歴一覧", admin_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %>
              </li>
            <% else %>
              <li class="mr-3">
                <%= link_to "About", about_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="mr-3">
                <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
              </li>
            <% end %>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-3 mb-3">
        <div class="row">
          <div class="mx-auto">
            CopyRight nagano_cake
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>